### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by hassanabidpk** [StravaKit/StravaKit#31]
I am getting following error.

```[!] Unable to satisfy the following requirements:

- `StravaKit` required by `Podfile`

Specs satisfying the `StravaKit` dependency were found, but they required a higher minimum deployment target.
```

Although, I am using `9.0` as minimum version for iOS. Is there any workaround for this ?

**Comment by brennanMKE** [comment]
@hassanabidpk This version of StravaKit uses Swift 3 which cannot run on iOS 9. I do have a Swift 2 branch you could try.
