### ISSUE TITLE
Unable to find a specification for `StravaKit`

### ISSUE THREAD

**Issue by timgcarlson** [StravaKit/StravaKit#5]
I'm trying to get StravaKit from CocoaPods, but it can't find the specification. I've confirmed that I'm able to load other dependencies, so I'm not sure why yours isn't working. Should this be working right now?

**Comment by brennanMKE** [comment]
@timgcarlson I am just seeing this now. My notifier did not tell me I had pending GitHub messages. I will look into this now.

**Comment by brennanMKE** [comment]
@timgcarlson Try the current release which is now Swift 3. See #9
