### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by agonzalezjr** [StravaKit/StravaKit#7]
Please 😄

**Comment by brennanMKE** [comment]
@agonzalezjr That is coming soon.

**Comment by brennanMKE** [comment]
@agonzalezjr I also plan on creating a 2nd related project which works on top of StravaKit which returns `ResultType` with `Success` or `Error` instead of using the completion handler which is common for older APIs. What do you think? Would you use that?

**Comment by brennanMKE** [comment]
@agonzalezjr I started the Swift 3 migration last night. See #9 for that progress.

**Comment by agonzalezjr** [comment]
Awesome

**Comment by brennanMKE** [comment]
The `Swifter` dependency for testing is proving to be a real problem. I am trying out alternatives.

**Comment by brennanMKE** [comment]
PR is pending.

**Comment by brennanMKE** [comment]
@agonzalezjr See the new v0.9.0 release. #9
